apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://semaphoreui.github.io/charts
    chart: semaphore
    targetRevision: 16.2.2
    helm:
      releaseName: semaphore
      values: |
        ingress:
          enabled: true
          className: traefik
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-production"
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hosts:
            - host: semaphore.starnix.net
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: semaphore-tls
              hosts:
                - semaphore.starnix.net

        persistence:
          enabled: true
          existingClaim: semaphore-workdir

        database:
          type: bolt
          persistence:
            enabled: true
            existingClaim: semaphore-database

        secrets:
          existingSecret: semaphore-secrets

        admin:
          create: true
          existingSecret: semaphore-secrets
          usernameKey: adminUsername
          fullnameKey: adminFullname
          emailKey: adminEmail
          passwordKey: adminPassword

        oidc:
          enable: true
          providers: {}

        extraEnvSecrets:
          SEMAPHORE_OIDC_PROVIDERS:
            secret: semaphore-secrets
            key: oidcProviders

  destination:
    server: https://kubernetes.default.svc
    namespace: semaphore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
