---
apiVersion: v1
kind: Namespace
metadata:
  name: privatebin

---
# Persistent Volume Claim using LONGHORN
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: privatebin-data-pvc
  namespace: privatebin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "longhorn" # FIXED

---
# PrivateBin Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: privatebin
  namespace: privatebin
  labels:
    app: privatebin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privatebin
  template:
    metadata:
      labels:
        app: privatebin
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: privatebin
        image: privatebin/nginx-fpm-alpine
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
            # Ephemeral storage request removed to avoid scheduler bugs
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15 # Increased slightly for safety
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
        volumeMounts:
        - name: privatebin-data-storage
          mountPath: "/srv/data"
      volumes:
      - name: privatebin-data-storage
        persistentVolumeClaim:
          claimName: privatebin-data-pvc

---
# PrivateBin Service
apiVersion: v1
kind: Service
metadata:
  name: privatebin
  namespace: privatebin
spec:
  selector:
    app: privatebin
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
# PrivateBin Ingress for Traefik
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: privatebin-ingress
  namespace: privatebin
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
  - host: privatebin.service.starnix.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: privatebin
            port:
              number: 8080
  tls:
  - hosts:
    - privatebin.service.starnix.net
    secretName: privatebin-tls-secret
