apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz-k8s-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.signoz.io
    chart: k8s-infra
    targetRevision: 0.15.0
    helm:
      releaseName: signoz-k8s-infra
      values: |
        global:
          cloud: others
          clusterName: talos
          deploymentEnvironment: production

        otelCollectorEndpoint: signoz-otel-collector.signoz.svc.cluster.local:4317
        otelInsecure: true

        presets:
          otlpExporter:
            enabled: true
          loggingExporter:
            enabled: false

        otelDeployment:
          config:
            receivers:
              prometheus/argocd:
                config:
                  global:
                    scrape_interval: 60s
                  scrape_configs:
                    - job_name: argocd-metrics
                      metrics_path: /metrics
                      scheme: http
                      static_configs:
                        - targets:
                          - argocd-application-controller-metrics.argocd.svc.cluster.local:8082
                          - argocd-server-metrics.argocd.svc.cluster.local:8083
                          - argocd-repo-server-metrics.argocd.svc.cluster.local:8084
            service:
              pipelines:
                metrics/argocd:
                  receivers: [prometheus/argocd]
                  processors: [batch]
                  exporters: []
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
