---
# 1. Namespace
# A dedicated namespace for Home Assistant resources.
apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
  labels:
    name: homeassistant

---
# 2. PersistentVolume (NFS)
# Defines the NFS volume that holds the application's configuration.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config-pv
spec:
  capacity:
    storage: 1Gi # Assuming a reasonable size; adjust if needed
  accessModes:
    - ReadWriteMany # Corresponds to Nomad's "multi-node-multi-writer"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "192.168.1.75"
    path: "/mnt/Store/nomad/homeassistant/config" # Path from your Nomad volume spec

---
# 3. PersistentVolumeClaim
# A claim for the NFS volume, which the Home Assistant pod will use.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: homeassistant-config-pv
  storageClassName: "" # Empty string to bind to the specific PV without a StorageClass

---
# 4. Deployment
# Manages the Home Assistant application pod.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: lscr.io/linuxserver/homeassistant:latest # Image from your Nomad spec
        ports:
        - containerPort: 8123
          name: http # Port exposed by the container
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Chicago"
        resources:
          requests:
            cpu: 200m # 2000 Nomad MHz is equivalent to 200m Kubernetes CPU
            memory: 4Gi # 4096 Nomad MB is equivalent to 4Gi Kubernetes memory
          limits:
            cpu: 2000m # Setting a reasonable limit
            memory: 4Gi
        volumeMounts:
        - name: config-volume
          mountPath: /config # Mount path inside the container
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: homeassistant-config

---
# 5. Service
# Exposes the Home Assistant deployment internally to the cluster.
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - protocol: TCP
      port: 8123 # Port the service listens on
      targetPort: 8123 # Port of the pod to which the service forwards traffic
  type: ClusterIP # Standard service type when using an Ingress

---
# 6. Ingress with NGINX and Cert-Manager
# Configures external access and automates SSL with cert-manager.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-ingress
  namespace: homeassistant
  annotations:
    # Use the cert-manager to automatically get a certificate
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Ensure SSL is enabled and redirects HTTP to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # Specify the backend protocol (Home Assistant expects HTTP, Ingress handles SSL)
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # Traefik's X-Forwarded-Proto is handled by nginx.ingress.kubernetes.io/backend-protocol
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ha.service.starnix.net
    secretName: homeassistant-tls-cert # cert-manager will create this secret
  rules:
  - host: ha.service.starnix.net
    http:
      paths:
      - path: / # Route all traffic for the host
        pathType: Prefix
        backend:
          service:
            name: homeassistant-service
            port:
              number: 8123 # Target the service port
