---
# Secret will be created separately using create-grocy-ldap-secrets.sh
# kubectl create secret generic grocy-ldap-secrets --namespace=grocy \
#   --from-literal=bind-dn="uid=svc_grocy,cn=users,cn=accounts,dc=starnix,dc=net" \
#   --from-literal=bind-password="your-password"

---
apiVersion: v1
kind: Namespace
metadata:
  name: grocy

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-config
  namespace: grocy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  namespace: grocy
spec:
  replicas: 1
  strategy:
    type: Recreate  # This prevents the volume conflict issue
  selector:
    matchLabels:
      app: grocy
  template:
    metadata:
      labels:
        app: grocy
    spec:
      containers:
      - name: grocy
        image: lscr.io/linuxserver/grocy:latest
        ports:
        - containerPort: 80
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Chicago"  # Adjusted for your location (Chalco, Nebraska)
        # LDAP Authentication Configuration for FreeIPA
        - name: GROCY_AUTH_CLASS
          value: "Grocy\\Middleware\\LdapAuthMiddleware"
        - name: GROCY_LDAP_ADDRESS
          value: "ldap://ipa1.starnix.net:389"
        - name: GROCY_LDAP_BASE_DN
          value: "cn=accounts,dc=starnix,dc=net"
        - name: GROCY_LDAP_BIND_DN
          valueFrom:
            secretKeyRef:
              name: grocy-ldap-secrets
              key: bind-dn
        - name: GROCY_LDAP_BIND_PW
          valueFrom:
            secretKeyRef:
              name: grocy-ldap-secrets
              key: bind-password
        - name: GROCY_LDAP_USER_FILTER
          value: "(&(objectClass=person)(objectClass=inetOrgPerson)(uid=*))"
        - name: GROCY_LDAP_UID_ATTR
          value: "uid"
        # Default permissions for LDAP users
        - name: GROCY_DEFAULT_PERMISSIONS
          value: "ADMIN"
        volumeMounts:
        - name: grocy-config
          mountPath: /config
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: grocy-config
        persistentVolumeClaim:
          claimName: grocy-config

---
apiVersion: v1
kind: Service
metadata:
  name: grocy
  namespace: grocy
spec:
  selector:
    app: grocy
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grocy-ingress
  namespace: grocy
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - grocy.starnix.net  # Replace with your desired domain
    secretName: grocy-tls
  rules:
  - host: grocy.starnix.net  # Replace with your desired domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grocy
            port:
              number: 80
