---
apiVersion: v1
kind: Namespace
metadata:
  name: wazuh

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: wazuh

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: default
  namespace: wazuh
spec:
  method: jwt
  mount: kubernetes
  jwt:
    role: cluster
    serviceAccount: vault-auth
    audiences:
      - vault

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wazuh-certs
  namespace: wazuh
spec:
  type: kv-v2
  mount: secret
  path: cluster/wazuh-certs
  vaultAuthRef: default
  destination:
    name: wazuh-certs
    create: true
  refreshAfter: 24h

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wazuh-secrets
  namespace: wazuh
spec:
  type: kv-v2
  mount: secret
  path: cluster/wazuh-secrets
  vaultAuthRef: default
  destination:
    name: wazuh-secrets
    create: true
  refreshAfter: 1h
